name: Build SunamoPaths

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoPaths
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoPaths/SunamoPaths.csproj

    - name: Build
      run: dotnet build SunamoPaths/SunamoPaths.csproj --configuration Release --no-restore

  test:
    name: Test SunamoPaths.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoPaths.Tests/SunamoPaths.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoPaths.Tests/SunamoPaths.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoPaths.Tests/SunamoPaths.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
